backend:
  name: github
  repo: koraycaliskan/44ai # GitHub kullanıcı adın ve depo adın
  branch: main # Depondaki ana dal adı (ana veya main)

media_folder: "images/uploads" # Ürün görsellerinin yükleneceği yer
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Ürünler"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Ürün Adı", name: "title", widget: "string" }
      - { label: "Özet Açıklama", name: "description", widget: "text" }
      - { label: "Ürün Görseli", name: "image", widget: "image" }
      - { label: "Ürün / İndirme Linki", name: "link", widget: "string" }
      - { label: "Fiyat / Durum", name: "price", widget: "string", default: "Yakında / Ücretsiz" }
